apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-name
  namespace: argocd
spec:
  project: default

  source:
    repoURL: app-repos
    # last commit
    targetRevision: HEAD
    # this path
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: app-name

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true