spring:
  datasource:
    url: jdbc:postgresql://128.199.138.228:5432/autopilot
    username: postgres
    password: 12345

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: smtp.gmail.com
    port: 587
    username: autopilotdeploy@gmail.com
    password: kdppupgaxgbgxter
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

error:
  url: http://localhost:8080/errors/
file:
  uploadPath: src/main/resources/images/

front:
  url: http://localhost:5174/email-sending?otp=